server:
  servlet:
    context-path: /api
spring:
  application.name: yrkesskade-skadeforklaring-api
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 8MB

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: /internal
      path-mapping.prometheus: prometheus
  metrics:
    export.prometheus.enabled: true
    tags:
      application: ${spring.application.name}