server:
  servlet:
    context-path: /api
spring:
  application.name: yrkesskade-skadeforklaring-api
  kafka:
    client-id: ${spring.application.name}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 8MB

kafka:
  topic:
    skadeforklaring-innsendt: yrkesskade.privat-yrkesskade-skadeforklaringinnsendt

integration:
  client:
    pdl:
      url: https://pdl-api.dev-fss-pub.nais.io/graphql
      client-id: dev-fss.pdl.pdl-api
    kodeverk:
      url: https://yrkesskade-kodeverk.dev.intern.nav.no

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: /internal
      path-mapping.prometheus: prometheus
  metrics:
    export.prometheus.enabled: true
    tags:
      application: ${spring.application.name}