logging.level.org.springframework: INFO
logging.level.no.nav: DEBUG

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    consumer:
      auto-offset-reset: earliest
      group-id: yrkesskade-skadeforklaring
    client-id: yrkesskade-skadeforklaring

kafka:
  topic:
    skadeforklaring-innsendt: test

no.nav.security.jwt.issuer:
  tokenx:
    discoveryurl: http://metadata-selvbetjening
    accepted_audience: aud-localhost