TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY}
      security.protocol: SSL
      basic:
        auth:
          credentials.source: USER_INFO
          user.info: ${KAFKA_SCHEMA_REGISTRY_USER}:${KAFKA_SCHEMA_REGISTRY_PASSWORD}
      ssl:
        truststore:
          type: JKS
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        key.password: ${KAFKA_CREDSTORE_PASSWORD}

storage.type: GCP

virusscan:
  url: http://clamav.clamav/scan


no.nav.security.jwt:
  issuer:
    tokenx:
      discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
      accepted_audience: dev-gcp:yrkesskade:yrkesskade-skadeforklaring-api
  client:
    registration:
      pdl:
        token-endpoint-url: https://tokendings.dev-gcp.nais.io/token
        grant-type: urn:ietf:params:oauth:grant-type:token-exchange
        authentication:
          client-id: ${TOKEN_X_CLIENT_ID}
          client-jwk: ${TOKEN_X_PRIVATE_JWK}
          client-auth-method: private_key_jwt
        token-exchange:
          audience: dev-fss:pdl:pdl-api
      pdl-maskintilmaskin:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://dev-fss.pdl.pdl-api/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt

