apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-yrkesskade-skadeforklaringinnsendt
  namespace: yrkesskade
  labels:
    team: yrkesskade
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 504
  acl:
    - team: yrkesskade
      application: yrkesskade-skadeforklaring-api
      access: write
    - team: yrkesskade
      application: yrkesskade-melding-mottak
      access: read
