name: "Test yrkesskade-skadeforklaring-api"
on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          "path": ~/.m2/repository
          "key": ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          "restore-keys": ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          "java-version": 11
      - name: compile and run tests
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}
        run: "mvn verify --settings .m2/maven-settings.xml --file pom.xml"